### ISSUE TITLE
Python 3.7 support

### ISSUE THREAD

**Issue by genofire** [pretix/pretix#1025]
I got this error on many a lot of different pages.

```
Sep 17 22:36:53 cetus gunicorn[5434]: ERROR 2018-09-17 20:36:53,009 django.request log Internal Server Error: /control/organizer/X/settings/display
Sep 17 22:36:53 cetus gunicorn[5434]: Traceback (most recent call last):
Sep 17 22:36:53 cetus gunicorn[5434]:   File "/var/pretix/venv/lib/python3.7/site-packages/kombu/utils/objects.py", line 42, in __get__
Sep 17 22:36:53 cetus gunicorn[5434]:     return obj.__dict__[self.__name__]
Sep 17 22:36:53 cetus gunicorn[5434]: KeyError: 'router'
Sep 17 22:36:53 cetus gunicorn[5434]: During handling of the above exception, another exception occurred:
Sep 17 22:36:53 cetus gunicorn[5434]: Traceback (most recent call last):
Sep 17 22:36:53 cetus gunicorn[5434]:   File "/var/pretix/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
Sep 17 22:36:53 cetus gunicorn[5434]:     response = get_response(request)
Sep 17 22:36:53 cetus gunicorn[5434]:   File "/var/pretix/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
Sep 17 22:36:53 cetus gunicorn[5434]:     response = self.process_exception_by_middleware(e, request)
Sep 17 22:36:53 cetus gunicorn[5434]:   File "/var/pretix/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
Sep 17 22:36:53 cetus gunicorn[5434]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
Sep 17 22:36:53 cetus gunicorn[5434]:   File "/var/pretix/venv/lib/python3.7/site-packages/pretix/control/permissions.py", line 64, in wrapper
Sep 17 22:36:53 cetus gunicorn[5434]:     return function(request, *args, **kw)
Sep 17 22:36:53 cetus gunicorn[5434]:   File "/var/pretix/venv/lib/python3.7/site-packages/django/views/generic/base.py", line 68, in view
Sep 17 22:36:53 cetus gunicorn[5434]:     return self.dispatch(request, *args, **kwargs)
Sep 17 22:36:53 cetus gunicorn[5434]:   File "/var/pretix/venv/lib/python3.7/site-packages/django/views/generic/base.py", line 88, in dispatch
Sep 17 22:36:53 cetus gunicorn[5434]:     return handler(request, *args, **kwargs)
Sep 17 22:36:53 cetus gunicorn[5434]:   File "/usr/lib64/python3.7/contextlib.py", line 74, in inner
Sep 17 22:36:53 cetus gunicorn[5434]:     return func(*args, **kwds)
Sep 17 22:36:53 cetus gunicorn[5434]:   File "/var/pretix/venv/lib/python3.7/site-packages/pretix/control/views/organizer.py", line 157, in post
Sep 17 22:36:53 cetus gunicorn[5434]:     regenerate_organizer_css.apply_async(args=(self.request.organizer.pk,))
Sep 17 22:36:53 cetus gunicorn[5434]:   File "/var/pretix/venv/lib/python3.7/site-packages/celery/app/task.py", line 535, in apply_async
Sep 17 22:36:53 cetus gunicorn[5434]:     **options
Sep 17 22:36:53 cetus gunicorn[5434]:   File "/var/pretix/venv/lib/python3.7/site-packages/celery/app/base.py", line 697, in send_task
Sep 17 22:36:53 cetus gunicorn[5434]:     router = router or amqp.router
Sep 17 22:36:53 cetus gunicorn[5434]:   File "/var/pretix/venv/lib/python3.7/site-packages/kombu/utils/objects.py", line 44, in __get__
Sep 17 22:36:53 cetus gunicorn[5434]:     value = obj.__dict__[self.__name__] = self.__get(obj)
Sep 17 22:36:53 cetus gunicorn[5434]:   File "/var/pretix/venv/lib/python3.7/site-packages/celery/app/amqp.py", line 606, in router
Sep 17 22:36:53 cetus gunicorn[5434]:     return self.Router()
Sep 17 22:36:53 cetus gunicorn[5434]:   File "/var/pretix/venv/lib/python3.7/site-packages/celery/app/amqp.py", line 287, in Router
Sep 17 22:36:53 cetus gunicorn[5434]:     return _routes.Router(self.routes, queues or self.queues,
Sep 17 22:36:53 cetus gunicorn[5434]:   File "/var/pretix/venv/lib/python3.7/site-packages/celery/app/amqp.py", line 601, in routes
Sep 17 22:36:53 cetus gunicorn[5434]:     self.flush_routes()
Sep 17 22:36:53 cetus gunicorn[5434]:   File "/var/pretix/venv/lib/python3.7/site-packages/celery/app/amqp.py", line 292, in flush_routes
Sep 17 22:36:53 cetus gunicorn[5434]:     self._rtable = _routes.prepare(self.app.conf.task_routes)
Sep 17 22:36:53 cetus gunicorn[5434]:   File "/var/pretix/venv/lib/python3.7/site-packages/celery/app/routes.py", line 136, in prepare
Sep 17 22:36:53 cetus gunicorn[5434]:     return [expand_route(route) for route in routes]
Sep 17 22:36:53 cetus gunicorn[5434]:   File "/var/pretix/venv/lib/python3.7/site-packages/celery/app/routes.py", line 136, in <listcomp>
Sep 17 22:36:53 cetus gunicorn[5434]:     return [expand_route(route) for route in routes]
Sep 17 22:36:53 cetus gunicorn[5434]:   File "/var/pretix/venv/lib/python3.7/site-packages/celery/app/routes.py", line 127, in expand_route
Sep 17 22:36:53 cetus gunicorn[5434]:     return MapRoute(route)
Sep 17 22:36:53 cetus gunicorn[5434]:   File "/var/pretix/venv/lib/python3.7/site-packages/celery/app/routes.py", line 36, in __init__
Sep 17 22:36:53 cetus gunicorn[5434]:     if isinstance(k, re._pattern_type):
Sep 17 22:36:53 cetus gunicorn[5434]: AttributeError: module 're' has no attribute '_pattern_type'
```

**Comment by rixx** [comment]
pretix doesn't work with Python 3.7 currently, as at least one dependency is not compatible with Python 3.7 yet (celery). This should probably be mentioned in the docs.

**Comment by genofire** [comment]
Jep, already recognised and found merged there: https://github.com/celery/celery/pull/4902

**Comment by genofire** [comment]
For me, you could close this issue now - but maybe you like to keep it for a python 3.7 todolist

**Comment by rixx** [comment]
This fix is included in the latest release, yes, but not all Python 3.7 relevant fixes are included yet, see also https://github.com/celery/celery/issues/4849#issuecomment-416794568 and the celery issue on project governance.

**Comment by bpcurse** [comment]
As some months have passed since the last update here, I would like to ask if Pretix can be installed on a system running python 3.7 atm? If not does anyone know an ETA?

**Comment by genofire** [comment]
RC1 for v4.3 is there :smile:

**Comment by knarrff** [comment]
Just had a very hard time getting pretix installed on a Debian system because of this. The problem is that Debian stable only comes with python3.5 (which isn't sufficient for pretalx), but Debian 'testing' (the next stable) will _only_ ship with python3.7. Installing pretix there, with some intermediate versions of python3.6 has not been fun. So, maybe 'upping' this a little in terms of priority?

**Comment by raphaelm** [comment]
Well, as long as a major dependency of ours is stuck on 3.6, it's unfortunately not up to what priority we assign this to :(

**Comment by genofire** [comment]
@raphaelm with the new release of celery, which dependency still stucks at 3.6 ?

**Comment by raphaelm** [comment]
@genofire I don't yet know, wanna try it out?

**Comment by genofire** [comment]
Look like, it works after running following update commands:
`pip3 install -U celery`:
```
Requirement already up-to-date: celery in /var/pretix/venv/lib/python3.7/site-packages (4.3.0)
Requirement already satisfied, skipping upgrade: pytz>dev in /var/pretix/venv/lib/python3.7/site-packages (from celery) (2018.5)
Requirement already satisfied, skipping upgrade: kombu<5.0,>=4.4.0 in /var/pretix/venv/lib/python3.7/site-packages (from celery) (4.5.0)
Requirement already satisfied, skipping upgrade: vine>=1.3.0 in /var/pretix/venv/lib/python3.7/site-packages (from celery) (1.3.0)
Requirement already satisfied, skipping upgrade: billiard<4.0,>=3.6.0 in /var/pretix/venv/lib/python3.7/site-packages (from celery) (3.6.0.0)
Requirement already satisfied, skipping upgrade: amqp<3.0,>=2.4.0 in /var/pretix/venv/lib/python3.7/site-packages (from kombu<5.0,>=4.4.0->celery) (2.4.2)
```
`pip3 install -U redis`:
```
Requirement already up-to-date: redis in /var/pretix/venv/lib/python3.7/site-packages (3.2.1)
```

**Comment by bpcurse** [comment]
With pretix 2.6.0 I am still getting:

```
ERROR: pretix 2.6.0 has requirement celery<4.2.0,>=4.1.1, but you'll have celery 4.3.0 which is incompatible.
ERROR: pretix 2.6.0 has requirement kombu==4.2.*, but you'll have kombu 4.5.0 which is incompatible.
ERROR: pretix 2.6.0 has requirement redis==2.10.5, but you'll have redis 3.2.1 which is incompatible.
```

**Comment by raphaelm** [comment]
This was merged after the release of 2.6.0. Hopefully, we can release 2.7.0 soon.
