### ISSUE TITLE
AttributeError: 'CountryField' object has no attribute 'db_collation' when updating to 4.0

### ISSUE THREAD

**Issue by Danyellsun** [pretix/pretix#2115]
```
python -m pretix migrate

Operations to perform:
  Apply all migrations: auth, badges, banktransfer, contenttypes, oauth2_provider, otp_static, otp_totp, paypal, pretix_pages, pretixapi, pretixbase, pretixdroid, pretixhelpers, pretixmultidomain, sessions, stripe, ticketoutputpdf
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/var/pretix/venv/lib/python3.6/site-packages/pretix/__main__.py", line 30, in <module>
    execute_from_command_line(sys.argv)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/var/pretix/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 201, in handle
    pre_migrate_state = executor._create_project_state(with_applied_migrations=True)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/db/migrations/executor.py", line 79, in _create_project_state
    migration.mutate_state(state, preserve=False)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/db/migrations/migration.py", line 89, in mutate_state
    operation.state_forwards(self.app_label, new_state)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/db/migrations/operations/fields.py", line 88, in state_forwards
    field = self.field.clone()
  File "/var/pretix/venv/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 512, in clone
    name, path, args, kwargs = self.deconstruct()
  File "/var/pretix/venv/lib/python3.6/site-packages/django_countries/fields.py", line 343, in deconstruct
    name, path, args, kwargs = super().deconstruct()
  File "/var/pretix/venv/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 1089, in deconstruct
    if self.db_collation:
AttributeError: 'CountryField' object has no attribute 'db_collation'
```
django-countries needed to be updated for the migration to work successfully.

**Comment by raphaelm** [comment]
Yup, correct, upgrading django-countries is the correct solution. We raised the required version in 36fd5e7d0. sorry for the trouble!
